### ISSUE TITLE
new Model DHO824 is missing

### ISSUE THREAD

**Issue by linuxuser234** [zelea2/rigol_vendor_bin#5]
There is a new model DHO824, would you please add it.

Thank you for your great work !!

**Comment by NullSense** [comment]
From a cursory skim of the project it seems all is missing is simply a string inclusion for the DHO824 model? https://github.com/zelea2/rigol_vendor_bin/blob/main/strings.c#L4

**Comment by linuxuser234** [comment]
> From a cursory skim of the project it seems all is missing is simply a string inclusion for the DHO824 model? https://github.com/zelea2/rigol_vendor_bin/blob/main/strings.c#L4

Yes, that's all

**Comment by zelea2** [comment]
Updated with the DHO824 model
